{% set setup_data = load_setup_py_data() %}
package:
  name: refine-contigs
  version: {{ setup_data['version'] }}

source:
  git_rev: {{ setup_data['version'] }}
  git_url: https://github.com/genomewalker/refine-contigs.git

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python>=3.7
    - setuptools
    - pip
  run:
    - python>=3.7
    - mmseqs2
    - pandas>=1.2.0
    - scipy>=1.5.2
    - networkx>=2.5
    - tqdm==4.50.0
    - PyYAML>=5.4
    - biopython>=1.68
    - pyranges>=0.0.97
    
test:
  commands:
    - refineC -h

about:
  home: https://github.com/genomewalker/refine-contigs
  summary: "A simple contig merging tool using minimus2"
  license: {{ setup_data['license'] }}
  license_file: LICENSE
